"use strict";
let bowshock = module.exports = {};
bowshock.helpers = require('./src/lib/helpers.js');
bowshock.apod = require('./src/lib/apod.js');
bowshock.asterank = require('./src/lib/asterank.js');
bowshock.donki = require('./src/lib/donki.js');
bowshock.exoPlanet = require('./src/lib/exoPlanet.js');
bowshock.epic = require('./src/lib/epic.js');
bowshock.geneLab = require('./src/lib/geneLab.js');
bowshock.nasaImgVideo = require('./src/lib/nasaImgVideo.js');
bowshock.satelliteSituationCenter = require('./src/lib/satelliteSituationCenter.js');
bowshock.earth = require('./src/lib/earth.js');
bowshock.helioviewer = require('./src/lib/helioviewer.js');
bowshock.patents = require('./src/lib/patents.js');
bowshock.skymorph = require('./src/lib/skymorph.js');
bowshock.mars = require('./src/lib/mars.js');
bowshock.eva = require('./src/lib/eva.js');
bowshock.neows = require('./src/lib/neows.js');
bowshock.eonet = require('./src/lib/eonet.js');
bowshock.ssd = require('./src/lib/ssd.js');
bowshock.trek = require('./src/lib/trek.js');
bowshock.techport = require('./src/lib/techport.js');